spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;IGNORECASE=TRUE;DATABASE_TO_UPPER=FALSE;
    username: arrety
    password: arrety
  h2:
    console:
      enabled: true
